name: Tests CI
#comment
on:
  workflow_dispatch:
  push:

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: action/checkout@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build Jar
        run: mvn test

